### ISSUE TITLE
[bug] The fire skill summon blocks continuously

### ISSUE THREAD

**Issue by JesKi13567** [Emafire003/LightWithin#14]
**Describe the bug**
The fire skill summon blocks continuously.

**To Reproduce**
1. Use Luxmutua Berry to change my skill to fire that summon fire blocks.
2. Use repeating command block `effect clear @a lightwithin:light_fatigue`
3. Use Luxintus Berry to active this skill twice, gap closely or even at same place.
4. Seeing the fire-style blocks show & disappear continuously.
5. Using tnt or mining these blocks does't stop it.

**Version information**
LightWithin mod version: 1.0.3
Minecraft Version: 1.20.4
Fabric API version: 0.96.11
(Usually not required, but could be helpful if you want)
Dependencies version: -

**Expected behavior**
Fire-style blocks become disappeared, permanently.

**Screenshots and files**
![continuous blocks](https://github.com/Emafire003/LightWithin/assets/113848030/a44228f7-691d-4b26-9511-913fde9b42e6)

**Additional context**
-

**Comment by Emafire003** [comment]
Well you aren't really supposed to activate it in quick succession. It looks like it is trying to restore the blocks that were there earlier, but since you activated twice in the same place it registered the original blocks and the ones placed by the first activation, and it's cycling through them. Since I don't think it is fixable without quite a bit of performance loss, I would simply suggest to either disable strcuture spawning or the regeneration of the terrain in the config file.

Also, I'm not sure I understood, it loops continously and it doesn't stop?

**Comment by JesKi13567** [comment]
> Well you aren't really supposed to activate it in quick succession. It looks like it is trying to restore the blocks that were there earlier, but since you activated twice in the same place it registered the original blocks and the ones placed by the first activation, and it's cycling through them. Since I don't think it is fixable without quite a bit of performance loss, I would simply suggest to either disable strcuture spawning or the regeneration of the terrain in the config file.
> 
> Also, I'm not sure I understood, it loops continously and it doesn't stop?

yes

**Comment by Emafire003** [comment]
It was an issue with StructurePlacerAPI, one of the libraries used internally (made by me anyway). The repeating permanent loop has been fixed, but of course if you use it in rapid succession the terrain won't go back to normal, and instead "absorb" the first structure's blocks, that will be placed back by the next one.
