### ISSUE TITLE
[Bug]  Game "desyncs" when Light power activation conditions are met

### ISSUE THREAD

**Issue by MLMII** [Emafire003/LightWithin#6]
My character rolls a defense style light, so I was testing it using a trapped zombie and whenever my health dropped low the game "desyncs" (sorry I'm not sure what the proper term is but basically enemies stop attacking, you can break blocks but not pick anything up, and you cannot quit out of the world and have to use taskmanager to force quit).

Doing so doesn't seem to produce a proper crash log that I could find.

Thank you for your time.

**Comment by Emafire003** [comment]
Uhm, that is really strange could send the server and client logs? (If you playe singleplayer only the "client" ones that are located in .minecraft/logs) Those of the time you played of course.

**Comment by MLMII** [comment]
I can't recreate the issue this afternoon so it might have been a Quilt issue (they released a new update today) ... I did update to the newest version you released today that had colored lights bundled as well.

Thank you for your time and sorry for the inconvenience.

**Comment by Emafire003** [comment]
Not at all, thank you for the report! To be fair I don't test the mod on quilt all that often, but it seems a very weird thing to occur, and since even you can't replicate I guess it has simply been a quirky phenomenon, so I'll close the issue for now. If it ever happens again, simply re-open the issue sending the logs and other uself info such as other mods used, loader and api version (of quilt/fabric) etc.
