### ISSUE TITLE
[Suggestion] Configurable Light Runes

### ISSUE THREAD

**Issue by TheGenericAllGamer** [Emafire003/LightWithin#8]
Besides this being an amazing and brilliant idea for a mod, I have one issue. A toggle for the runes that appear onscreen (upon light activation) to be added for those that prefer a cleaner screen. Perhaps even being able to change what appears when your light activates.

**Comment by Emafire003** [comment]
You are in luck, I was finishing up the new release, one of the last few before beta. At some point I intended to add a toggle, but the forgot to. Thanks for reminding me! Anyway, to change what appears you can use a resource pack, just like you do with vanilla, only the the images you will have to edit are located in `assets/lightwithin/lights/runes/<the_rune>.png` instead of `assets/minecraft/stuff`
